---
keycloak:
  extraEnv: |
    - name: PROXY_ADDRESS_FORWARDING
      value: 'true'
    - name: KEYCLOAK_USER
      value: "admin"
  extraEnvFrom: |
    - secretRef:
        name: keycloak-admin
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
      kubernetes.io/ingress.class: traefik-cert-manager
    rules:
    - host: keycloak.kam.obmondo.com
      paths:
        - /
    tls:
    - secretName: keycloak-kam-ssl
      hosts:
      - keycloak.kam.obmondo.com
