kube-prometheus-stack:
  prometheus:
    prometheusSpec:
      storageSpec:
        volumeClaimTemplate:
          spec:
            storageClassName: rook-ceph-block
            resources:
              requests:
                storage: 10Gi
