traefik:
  deployment:
    kind: DaemonSet
  ports:
    websecure:
      hostPort: 443
    web:
      hostPort: 80
  service:
    type: NodePort
    externalIPs:
      - 176.9.67.43
  additionalArguments:
    - "--providers.kubernetesIngress.ingressClass=traefik-cert-manager"
    - "--metrics.prometheus"
