apiVersion: v1
kind: ConfigMap
metadata:
  name: teleport-cluster
data:
  teleport.yaml: |
    teleport:
      log:
        severity: INFO
        output: stderr
    auth_service:
      enabled: true
      cluster_name: teleport.obmondo.com
      authentication:
        require_session_mfa: yes
        type: local
        second_factor: u2f
        u2f:
          app_id: https://teleport.obmondo.com:443
          facets:
          - https://teleport.obmondo.com:443
          - https://teleport.obmondo.com
          - teleport.obmondo.com:443
          - teleport.obmondo.com
    kubernetes_service:
      enabled: true
      listen_addr: 0.0.0.0:3027
      labels:
    proxy_service:
      public_addr: 'teleport.obmondo.com:443'
      kube_listen_addr: 0.0.0.0:3026
      enabled: true
      acme:
        enabled: true
        email: info@enableit.dk
    ssh_service:
      enabled: true
