stages:
  - lint
  - diff
  - build

lint_sh:
  stage: lint
  image: koalaman/shellcheck-alpine
  script:
    - 'find . -name \*.sh -o -name \*.bash | xargs shellcheck'
  only:
  - merge_requests

lint_yaml:
  stage: lint
  image: runejuhl/alpine-ci
  script:
    - ./bin/check_yaml.rb
  only:
  - merge_requests

check_diff:
  image: registry.obmondo.com/obmondo/dockerfiles/obmondo-build:latest
  stage: diff
  script:
    - ./bin/script.sh
  only:
  - merge_requests

build:
  stage: build
  image: dtzar/helm-kubectl
  only:
    refs:
      - 'merge_requests'
  script:
    - bash helm-chart-cache.sh -u Obmondo -p $PASSWORD -r ghcr.io/Obmondo
