---
stages:
  - lint
  - diff
  - build

lint_sh:
  stage: lint
  image: koalaman/shellcheck-alpine
  script:
    - 'find . -name \*.sh -o -name \*.bash | xargs shellcheck'
  only:
    - merge_requests

lint_yamllint:
  stage: lint
  image: registry.obmondo.com/obmondo/dockerfiles/yamllint:latest
  script:
    - yamllint --strict --config-file .yamllint .
  only:
    - merge_requests

check_diff:
  image: registry.obmondo.com/obmondo/dockerfiles/obmondo-build:latest
  stage: diff
  script:
    - ./bin/script.sh
  only:
    - merge_requests

build:
  stage: build
  image: registry.obmondo.com/obmondo/dockerfiles/obmondo-build:latest
  only:
    refs:
      - 'merge_requests'
  script:
    - echo "$CI_COMMIT_REF_NAME"
    - bash helm-chart-cache.sh -u Obmondo -p $PASSWORD -r ghcr.io/Obmondo
