---
stages:
  - lint
  - diff
  - build
  - deploy

lint:markdown:
  stage: lint
  image: registry.obmondo.com/obmondo/dockerfiles/markdownlint:latest
  script:
    - markdownlint --config .markdownlint  --ignore 'build/vendor/**' --ignore 'build/kube-prometheus/**'
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

lint_sh:
  stage: lint
  image: koalaman/shellcheck-alpine
  script:
    - 'find . -not -path ./build/kube-prometheus/libraries/\* -a -not -path ./build/vendor/\* -name \*.sh -o -name \*.bash | xargs shellcheck'
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

lint_yamllint:
  stage: lint
  image: registry.obmondo.com/obmondo/dockerfiles/yamllint:latest
  script:
    - yamllint --strict --config-file .yamllint .
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

lint:jsonnetfmt:
  stage: lint
  image:
    name: bitnami/jsonnet:latest
    entrypoint: ['']
  script:
    - './bin/lint-jsonnetfmt.sh'
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

check_diff:
  image: registry.obmondo.com/obmondo/dockerfiles/obmondo-build:latest
  stage: diff
  script:
    - ./bin/script.sh
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

# FIXME: this is disabled for now because the build-jsonnet script expects a
# cluster config, which we can't do, since it requires us to clone a remote,
# which happens in the deploy pipeline. We could test for changes in just
# clusters we have vars config files for in this repo, but that seems a bit
# silly...
#
# diff:jsonnet:
#   image: registry.obmondo.com/obmondo/dockerfiles/obmondo-build:latest
#   stage: diff
#   script:
#     - ./bin/build-jsonnet.sh
#   rules:
#     - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

build:
  stage: build
  image: registry.obmondo.com/obmondo/dockerfiles/obmondo-build:latest
  script:
    - echo "$CI_COMMIT_REF_NAME"
    - bash helm-chart-cache.sh -u Obmondo -p $PASSWORD -r ghcr.io/Obmondo
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

git:push:
  stage: deploy
  image:
    name: registry.obmondo.com/obmondo/dockerfiles/kubernetes-build:1644319710
  script:
    - ./bin/deploy.sh ./.deploy_config
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $KUBERNETES_CONFIG_REPO_TOKEN && $KUBERNETES_CONFIG_REPO_URL'
