cluster:
  name: testing
  shortName: testing

argo-cd:
  secret:
    createSecret: true
  repo:
    auth:
      git: https
    data:
      url: https://gitlab.enableit.dk/kubernetes/kubernetes-config-enableit
      name: obmondo-helm-values
    charts:
      url: https://gitlab.enableit.dk/kubernetes/argocd-apps
      name: obmondo-helm-charts
  controller:
    replicas: 3
  repoServer:
    replicas: 6
