{{ if .Values.networkpolicies }}
apiVersion: crd.projectcalico.org/v1
kind: NetworkPolicy
metadata:
  name: default.aws-efs-csi-driver
  namespace: aws
spec:
  order: 100
  selector:
    app.kubernetes.io/name == 'aws-efs-csi-driver'
  types:
  - Egress
  egress:
  # Allow access to the apiserver
  - action: Allow
    protocol: TCP
    destination:
      selector: kubernetes.io/role == 'master'
      namespaceSelector: global()
      ports:
      - 443
  # Connect to kube2iam
  - action: Allow
    protocol: TCP
    destination:
      ports:
      - 8181
      selector: kubernetes.io/role in { 'node', 'master' }
      namespaceSelector: global()
{{ end }}
