apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  project: default
  source:
    path: argocd-clusters-managed/k8s-nuc8/
    repoURL: ssh://git@gitlab.enableit.dk:2223/kubernetes/argocd-apps.git
    targetRevision: HEAD
    helm:
      valueFiles:
      - values.yaml
      - ../../argocd-clusters-managed/k8s-nuc8/values-kube-prometheus-stack.yaml
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
