apiVersion: crd.projectcalico.org/v1
kind: NetworkPolicy
metadata:
  name: default.sftpdb
  namespace: {{ .Values.namespace }}
spec:
  order: 100
  selector:
    app.kubernetes.io/name == 'postgres-operator'
  types:
  - Egress
  egress:
  # Allow access to the apiserver
  - action: Allow
    protocol: TCP
    destination:
      selector: kubernetes.io/role == 'master'
      namespaceSelector: global()
      ports:
      - 443
  - action: Allow
    protocol: TCP
    destination:
      selector: application == 'spilo'
      namespaceSelector: all()
      ports:
      - 5432 # PostgreSQL
      - 8008 # Patroni
