apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rook
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: rook
  project: default
  source:
    path: argocd-helm-charts/rook
    repoURL: ssh://git@gitlab.enableit.dk:2223/kubernetes/argocd-apps.git
    targetRevision: HEAD
    helm:
      valueFiles:
      - values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true

