apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rook-ceph
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: rook-ceph
  project: default
  source:
    path: argocd-helm-charts/rook-ceph
    repoURL: <repo_url>
    targetRevision: HEAD
    helm:
      valueFiles:
      - values.yaml
      - ../../argocd-clusters-managed/<cluster_name>/values-cert-manager.yaml
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=true
