{{- if .Values.issuer.enabled -}}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  {{ if .Values.issuer.production }}
  name: letsencrypt
  {{ else }}
  name: letsencrypt-staging
  {{ end }}
spec:
  acme:
    email: {{ .Values.issuer.issuerEmail }}
    preferredChain: ""
    privateKeySecretRef:
      name: {{ .Values.issuer.secret }}
    {{ if .Values.issuer.production }}
    server: https://acme-v02.api.letsencrypt.org/directory
    {{ else }}
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    {{ end }}
    solvers:
    - http01:
        ingress:
          class: traefik-cert-manager
{{ end }}
