apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitlab-runner
  namespace: serviceless
spec:
  destination:
    namespace: gitlab-runner
    server: https://kubernetes.default.svc
  project: default
  source:
    path: argocd-helm-charts/gitlab-runner
    repoURL: ssh://git@gitlab.enableit.dk:2223/kubernetes/argocd-apps.git
    targetRevision: HEAD
    helm:
      valueFiles:
      - values.yaml
      - ../../argocd-clusters-managed/htzfsn1-kam/values-gitlab-runner.yaml
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
