apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metrics-server
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  project: default
  source:
    path: argocd-helm-charts/metrics-server
    repoURL: https://github.com/blackwoodseven/k8s-init.git
    targetRevision: HEAD
    helm:
      valueFiles:
      - values.yaml
