apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rook-ceph
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: rook-ceph
  project: default
  source:
    path: argocd-helm-charts/rook
    repoURL: ssh://git@gitlab.enableit.dk:2223/kubernetes/argocd-apps.git
    targetRevision: rook
    helm:
      valueFiles:
      - values.yaml
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
