apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  project: default
  source:
    path: argocd-helm-charts/sealed-secrets
    repoURL: ssh://git@gitlab.enableit.dk:2223/kubernetes/argocd-apps.git
    targetRevision: HEAD
    helm:
      valueFiles:
      - values.yaml
