apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: teleport-cluster
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: teleport-cluster
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: argocd-helm-charts/teleport-cluster
    repoURL: 'ssh://git@gitlab.enableit.dk:2223/kubernetes/argocd-apps.git'
    targetRevision: HEAD
    helm:
      valueFiles:
      - values.yaml
      - ../../argocd-clusters-managed/htzfsn1-kam/values-teleport-cluster.yaml
  syncPolicy:
    syncOptions:
    - ApplyOutOfSyncOnly=true
    - CreateNamespace=true
