{{ if .Values.networkpolicies }}
apiVersion: crd.projectcalico.org/v1
kind: NetworkPolicy
metadata:
  name: default.cerebro
#  namespace: {{ .Values.namespace }}
  namespace: graylog
spec:
  order: 100
  selector:
    app == 'cerebro'
  types:
  - Ingress
  - Egress
  ingress:
  # Allow traefik to connect the the web endpoint
  - action: Allow
    protocol: TCP
    source:
#      selector: app.kubernetes.io/name == 'traefik'
#      namespaceSelector: projectcalico.org/name == 'traefik'
      nets:
      - '100.0.0.0/8'
    destination:
      ports:
      - 9000
  egress:
  # Connections to opensearch nodes
  - action: Allow
    protocol: TCP
    destination:
      selector: app.kubernetes.io/name == 'opensearch'
      ports:
      - 9200
{{ end }}
