apiVersion: v1
data:
  script: |-
    #! /bin/bash
    set -euo pipefail

    BUCKET="bw7-incomming-data-dmz"

    if [ ! -d /home/.queue/ ]; then
      echo Creating directory: /home/.queue/
      mkdir -p /home/.queue/
    fi

    echo Starting efs2s3 script
    while true; do
      FILE=$(find /home/.queue/ -type f | shuf -n 1)
      if [ -z "$FILE" ]; then # $FILE is empty
        # Sleep between 0.1 and 2.9 seconds
        sleep $(($RANDOM%3)).$(($RANDOM%10))
      else
        DEST=$(echo $FILE | perl -pe 's!/home/\.queue/!!')
        echo Copying $FILE to s3://$BUCKET/$DEST
        aws s3 cp $FILE s3://$BUCKET/$DEST
        rm $FILE
      fi
    done
  config: |
    [profile default]
    credential_source = Ec2InstanceMetadata
    region = eu-west-1
kind: ConfigMap
metadata:
  name: efs2s3
  namespace: {{ .Values.namespace }}

