apiVersion: v1
data:
  proftpd.conf: |-
    UseIPv6                         off
    IdentLookups                    off
    UseReverseDNS                   off
    DeferWelcome                    on
    ServerName                      "Blackwood Seven"
    ServerType                      standalone

    MultilineRFC2228                on
    DefaultServer                   on
    ShowSymlinks                    on

    TimeoutNoTransfer               600
    TimeoutStalled                  600
    TimeoutIdle                     120

    ListOptions                     "-l"

    # Use this to jail all users in their homes
    DefaultRoot                     ~

    RequireValidShell               off

    MaxInstances                    30

    # Set the user and group that the server normally runs at.
    User                            proftpd
    Group                           nogroup

    Umask                           007  007
    # Normally, we want files to be overwriteable.
    AllowOverwrite                  on

    # Uncomment this if you are using NIS or LDAP via NSS to retrieve passwords:
    PersistentPasswd                off

    # Send the log info out of the pod
    TransferLog		/dev/stderr

    # No need to update wtmp
    WtmpLog                         off

    SetEnv		TZ :/etc/localtime

    ControlsEngine	off
    DelayEngine		off

    # Enable SFTP
    LoadModule mod_sftp.c
    SFTPEngine on
    Port 2222

    # Only support the secure algorithms
    # The lists are primarily based on the CIS benchamrks
    SFTPCiphers aes128-ctr aes192-ctr aes256-ctr
    SFTPDigests hmac-sha2-256 hmac-sha2-512
    SFTPKeyExchanges ecdh-sha2-nistp521 ecdh-sha2-nistp384 ecdh-sha2-nistp256 diffie-hellman-group18-sha512 diffie-hellman-group16-sha512 diffie-hellman-group14-sha256 diffie-hellman-group-exchange-sha256

    SFTPCompression on

    SFTPDHParamFile /mnt/key/dhparams.pem

    # Allow logging to symlinks, since /dev/stderr is a symlink
    AllowLogSymlinks on

    # Ignore the permissions+timestamp+etended attributes send by the client
    # And ignore requests to set that kind of metadata
    # And disable support for extension negotiation
    SFTPOptions IgnoreSCPUploadPerms IgnoreSCPUploadPerms IgnoreSFTPSetExtendedAttributes IgnoreSFTPSetOwners IgnoreSFTPSetPerms IgnoreSFTPSetTimes IgnoreSFTPUploadExtendedAttributes IgnoreSFTPUploadPerms InsecureHostKeyPerms

    # No DSA key, since it is less secure then the alternatives
    # No ED25519 key, since ssh-keygen cannot store it in PEM format, which is required by proftpd
    SFTPHostKey /mnt/key/ssh_host_rsa_key
    SFTPHostKey /mnt/key/ssh_host_ecdsa_key

    # Send the log info out of the pod
    SFTPLog /dev/stderr

    # Security
    SFTPRekey required
    SFTPTrafficPolicy medium
    # And we also need some limit entries
    #PathAllowFilter ^[A-Za-z0-9_./-]+$

    AuthPAM off

    LoadModule mod_sql.c
    LoadModule mod_sql_postgres.c
    LoadModule mod_sftp_sql.c

    # Only authenticate using SQL
    AuthOrder mod_sql.c

    SQLEngine               auth
    SQLAuthTypes            crypt
    SQLBackend              postgres
    SQLConnectInfo          {{ .Values.pgsql.database_name }}@{{ .Values.pgsql.host }} {{ .Values.proftpd.database_user }} %{env:POSTGRES_PASSWORD}
    #SQLConnectInfo          proftpd@sre-sftpdb.sftp.svc.cluster.local. proftpd %{env:POSTGRES_PASSWORD}
    SQLNamedQuery           get-user-authorized-keys SELECT "sftpuserkeys FROM users WHERE userid='%U'"
    SFTPAuthorizedUserKeys  sql:/get-user-authorized-keys

    # Completely hide any .ftpaccess files
    <Directory /home/>
      HideFiles "\.ftpaccess(\.tmp)?$"
      <Limit ALL>
        IgnoreHidden on
      </Limit>
    </Directory>

    # Disable some of the ftp commands. Basically mkdir, rmdir, chmod, chuser, rename and equivalents
    <Limit MFMT MKD RMD XMKD XRMD SITE_CHGRP SITE_CHMOD SITE_MKDIR SITE_RMDIR SITE_SYMLINK SITE_UTIME SYST>
      DenyAll
    </Limit>

    LoadModule mod_clamav.c
    ClamAV     on
    # Looking up the dns name of the ClamAV service does not work
    # So we are using the default k8s environment variables instead
    ClamServer %{env:SFTP_CLAMAV_SERVICE_HOST}
    ClamPort   %{env:SFTP_CLAMAV_SERVICE_PORT}
    ClamStream on

kind: ConfigMap
metadata:
  name: proftpd
  namespace: {{ .Values.namespace }}
