apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: sftp-cron
  namespace: {{ .Values.namespace }}
spec:
  schedule: {{ .Values.schedule | quote }}
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 10
  successfulJobsHistoryLimit: 5
  startingDeadlineSeconds: 180
  suspend: false
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: sftp-cron
        spec:
          containers:
          - name: main
            image: {{ .Values.cron.image }}
            imagePullPolicy: IfNotPresent
            command:
            - /usr/bin/perl
            - /mnt/script
            env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: {{ .Values.cron.password_key | quote }}
                  name: {{ .Values.cron.password_secret | quote }}
            resources:
              limits:
                cpu: 100m
                memory: 256Mi
              requests:
                cpu: 100m
                memory: 64Mi
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                add:
                - CAP_CHOWN
                drop:
                - all
              privileged: false
            volumeMounts:
            - name: sftp-cron
              mountPath: /mnt
            - mountPath: /home
              name: shared-home
          restartPolicy: OnFailure
          securityContext:
            runAsNonRoot: false
            runAsUser: 0
          volumes:
          - name: sftp-cron
            configMap:
              name: sftp-cron
          - name: shared-home
            persistentVolumeClaim:
              claimName: sftp-data

