apiVersion: crd.projectcalico.org/v1
kind: NetworkPolicy
metadata:
  name: default.clamav
  namespace: {{ .Values.namespace }}
spec:
  order: 100
  selector:
    app.kubernetes.io/name == 'clamav'
  types:
  - Ingress
  - Egress
  ingress:
  - action: Allow
    protocol: TCP
    source:
      selector: app == 'proftpd'
    destination:
      ports:
      - 3310
  egress:
  - action: Allow
    protocol: TCP
    destination:
      ports:
      - 443 # Downloading ClamAV Databases
