apiVersion: v1
kind: PersistentVolume
metadata:
  name: sftp-data
  namespace: {{ .Values.namespace }}
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  nfs:
    server: {{ .Values.nfs.server }}
    path: "/"
  mountOptions:
    - nfsvers=4.1

