apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sftp-data
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 1Ti
