apiVersion: v1
kind: Service
metadata:
  annotations:
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.dns_name }}
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
  name: proftpd
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - name: sftp
    port: 2222
    protocol: TCP
  selector:
    app: proftpd
  type: LoadBalancer

