{{ if .Values.networkpolicies }}
apiVersion: crd.projectcalico.org/v1
kind: NetworkPolicy
metadata:
  name: default.k8s-event-logger
  namespace: logging
spec:
  order: 100
  selector:
    app.kubernetes.io/name == 'k8s-event-logger'
  types:
  - Egress
  egress:
  # Allow filebeat to get instance metadata from the apiserver
  - action: Allow
    protocol: TCP
    destination:
      selector: kubernetes.io/role == 'master'
      namespaceSelector: global()
      ports:
      - 443
{{ end }}
