# https://rook.io/docs/rook/v1.5/ceph-cluster-crd.html#host-based-cluster
apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  cephVersion:
    # see the "Cluster Settings" section below for more details on which image of ceph to run
    image: ceph/ceph:v15.2.9
  dataDirHostPath: /var/lib/rook
  mon:
    count: 3
    allowMultiplePerNode: false
  storage:
    useAllNodes: false
    useAllDevices: false
    nodes:
    - name: "htzsb44fsn1a.enableit.dk"
      devices:
      - name: "sdc2"
      - name: "sdb2"
    - name: "htzsb45fsn1a.enableit.dk"
      devices:
      - name: "sdc2"
      - name: "sdd2"
    - name: "htzsb45fsn1b.enableit.dk"
      devices:
      - name: "sda2"
      - name: "sdb2"
  monitoring:
    enabled: true
