apiVersion: v2
name: argo-cd
version: 1.0.0
dependencies:
  - name: argo-cd
    version: 2.17.0
    repository: https://argoproj.github.io/argo-helm
    # see versions here: https://github.com/argoproj/argo-helm/blob/master/charts/argo-cd/Chart.yaml
