# Examples for adding git repo
#        - type: git
#          url: https://github.com/someuser/k8s-repo.git
#          passwordSecret:
#            name: argo-cd-someuser-github
#            key: password
#          usernameSecret:
#            name: argo-cd-someuser-github
#            key: username

argo-cd:
  # to make this chart work with helm 3 - it does still install CRDs
  installCRDs: false
  # find latest tag here: https://github.com/argoproj/argo-helm/blob/master/charts/argo-cd/Chart.yaml (AppVersion)
  dex:
    enabled: false
  repoServer:
    replicas: 1
    autoscaling:
      enabled: true
