{{ if .Values.certificate }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: sonarqube-tls
  namespace: sonarqube
spec:
  dnsNames:
  - sonarqube.dmz.bw7.io
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt
  secretName: sonarqube-tls
  usages:
  - digital signature
  - key encipherment
{{ end }}
