apiVersion: v1
data:
  script: |-
    #!/usr/bin/bash

    BACKUP_BUCKET={{ .Values.backup.bucket }}
    DELETE_DAYS=180
    PGHOST=sonarqube-postgresql
    PGUSER=sonarqube

    echo "First, dump the database"
    TIMESTAMP=$(date +%Y%m%d%H%M%S)
    echo $PGHOST:5432:sonarqube:$PGUSER:$PG_PASS > ~/.pgpass
    chmod 0600 ~/.pgpass
    pg_dump -h $PGHOST -U $PGUSER sonarqube --format=plain --compress=9 --file=/tmp/sonarqube-$TIMESTAMP.sql.gz --create --clean

    echo "Next, copy the database dump to S3"
    aws s3 cp /tmp/sonarqube-$TIMESTAMP.sql.gz s3://$BACKUP_BUCKET/

    echo "Next, get the list of backup stored in S3"
    LIST=$(aws s3 ls s3://$BACKUP_BUCKET/ |sed 's/^.* //'| sort)

    LIST_SIZE=$(echo $LIST | wc -w)
    let NUM=$LIST_SIZE-$DELETE_DAYS
    if [ $NUM -gt 0 ]; then
      echo "There are $NUM backup(s) that needs to be deleted from S3"
    else
      echo "There are no backups in S3, that needs to be deleted"
      exit
    fi

    for file in $LIST; do
      aws s3 rm s3://$BACKUP_BUCKET/$file
      let "NUM--"
      if [ $NUM -lt 1 ]; then
        exit
      fi
    done
kind: ConfigMap
metadata:
  name: backup-sonarqube-db
  namespace: sonarqube
