apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: teleport-kube-agent
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: obmondo
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: argocd-helm-charts/teleport-kube-agent
    repoURL: 'https://gitlab.enableit.dk/kubernetes/argocd-apps.git'
    targetRevision: HEAD
    helm:
      valueFiles:
      - values.yaml
      - ../../argocd-clusters-managed/htzhel1-kbm/values-teleport-kube-agent.yaml
  syncPolicy:
    syncOptions:
    - ApplyOutOfSyncOnly=true
    - CreateNamespace=true
