{{ if .Values.networkpolicies }}
apiVersion: crd.projectcalico.org/v1
kind: NetworkPolicy
metadata:
  name: default.graylog
#  namespace: {{ .Values.namespace }}
  namespace: graylog
spec:
  order: 100
  selector:
    app.kubernetes.io/name == 'graylog'
  types:
  - Ingress
  - Egress
  ingress:
  # Ingoing filebeat traffik
  - action: Allow
    protocol: TCP
    destination:
      ports:
      - 5044
  # Allow traefik to connect the the web endpoint
  - action: Allow
    protocol: TCP
    source:
      selector: app.kubernetes.io/name == 'traefik'
      namespaceSelector: projectcalico.org/name == 'traefik'
    destination:
      ports:
      - 9000
  egress:
  # Connections to opensearch nodes
  - action: Allow
    protocol: TCP
    destination:
      ports:
      - 9200
      nets:
      - '100.0.0.0/8'
      - '0.0.0.0/0'
  # AWS and Google API endpoint
  - action: Allow
    protocol: TCP
    destination:
      ports:
      - 443
      nets:
      - 52.0.0.0/8 # AWS is using several IP's in this range
      - 54.0.0.0/8 # AWS is using several IP's in this range
      - 74.125.0.0/16 # GoogleAPIs
      - 140.82.121.3
      - 185.199.111.133
      - 140.82.121.4
      - 185.199.110.133
      - 185.199.108.133
  - action: Allow
    protocol: TCP
    destination:
      ports:
      - 27017
#      selector: app.kubernetes.io/name == 'mongodb'
      nets:
      - '100.0.0.0/8'
  # Allow access to the apiserver
  - action: Allow
    protocol: TCP
    destination:
      selector: kubernetes.io/role == 'master'
      namespaceSelector: global()
      ports:
      - 443
{{ end }}
