{{ if .Values.networkpolicies }}
apiVersion: crd.projectcalico.org/v1
kind: NetworkPolicy
metadata:
  name: default.mongodb
#  namespace: {{ .Values.namespace }}
  namespace: graylog
spec:
  order: 100
  selector:
    app.kubernetes.io/name == 'mongodb'
  types:
  - Ingress
  ingress:
  # Allow traefik to connect the the web endpoint
  - action: Allow
    protocol: TCP
    source:
      selector: app.kubernetes.io/name == 'graylog'
    destination:
      ports:
      - 27017
{{ end }}
