networkpolicies: false
certificate: false
configmap: false
cronjob: false
sonarqube:
  postgresql:
    existingSecret: postgres.obmondo-posgresql.credentials.postgresql.acid.zalan.do
    existingSecretPasswordKey: password
    enabled: false