networkpolicies: false
sonarqube:
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
  # NOT using the default, included postgresql instance for this setup. We depend on postgres-operator pgsql instance instead.
  postgresql:
    enabled: false
  jdbcOverwrite:
    enable: true
    jdbcUrl: "jdbc:postgresql://obmondo-postgresql/sonarqube?socketTimeout=1500"
    jdbcUsername: "sonarqube_admin"
    jdbcSecretPasswordKey: password
    jdbcSecretName: sonarqube-admin.obmondo-postgresql.credentials.postgresql.acid.zalan.do

ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    kubernetes.io/ingress.class: traefik-cert-manager
  hosts:
  - sonarqube.kam.obmondo.com
  tls:
  - secretName: argocd-ssl
    hosts:
    - sonarqube.kam.obmondo.com







