networkpolicies: false
certificate: false
configmap: false
cronjob: false
sonarqube:
  postgresql:
    existingSecret: postgres.obmondo-postgresql.credentials.postgresql.acid.zalan.do
    existingSecretPasswordKey: password
    enabled: false
    postgresqlServer: "obmondo-postgresql.sonarqube.svc.cluster.local"
    postgresqlUsername: "postgres"