networkpolicies: false
certificate: false
configmap: false
cronjob: false
sonarqube:
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
  postgresql:
    enabled: false
  jdbcOverwrite:
    enable: true
    jdbcUrl: "jdbc:postgresql://obmondo-postgresql/sonarqube?socketTimeout=1500"
    jdbcUsername: "sonarqube_admin"
    jdbcSecretPasswordKey: password
    jdbcSecretName: sonarqube-admin.obmondo-postgresql.credentials.postgresql.acid.zalan.do
