networkpolicies: false
sonarqube:
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
  postgresql:
    enabled: false
    existingSecret: postgresql-credentials
    existingSecretPasswordKey: postgresql-password
    postgresqlServer: sonarqube-postgresql
    postgresqlUsername: sonarqube
    postgresqlDatabase: sonarqube
  persistence:
    enabled: true
    storageClass: encryptedgp2
  image:
    tag: 8.9.0-community
  deploymentStrategy:
    type: Recreate

postgresql:
  persistence:
    size: 20Gi
    storageClass: encryptedgp2
  image:
    tag: 13.3.0
  global:
    postgresql:
      postgresqlDatabase: sonarqube
      postgresqlUsername: sonarqube
      existingSecret: postgresql-credentials

nginx:
  containerPorts:
    http: 8080
    https: 8443
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
  serverBlock: |-
    server {
      server_name sonarqube.dmz.bw7.io;
      listen 0.0.0.0:8080;
      return 301 https://$host$request_uri;
    }
    server {
      listen 0.0.0.0:8080 default_server;
      return 404;
    }
    server {
      server_name sonarqube.dmz.bw7.io;
      listen 0.0.0.0:8443 ssl;
      ssl_certificate /certificate/tls.crt;
      ssl_certificate_key /certificate/tls.key;
      location / {
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_pass http://sonarqube-sonarqube:9000;
      }
    }
    server {
      listen 0.0.0.0:8443 default_server;
      ssl_reject_handshake on;
    }
  service:
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
      service.beta.kubernetes.io/aws-load-balancer-internal: "true"
      service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: '*'
      service.beta.kubernetes.io/aws-load-balancer-type: nlb
      external-dns.alpha.kubernetes.io/hostname: sonarqube.dmz.bw7.io.
  extraVolumes:
  - name: certificate
    secret:
      secretName: sonarqube-tls
  extraVolumeMounts:
  - name: certificate
    mountPath: /certificate
    readOnly: true

backup:
  role:     arn:aws:iam::438423213058:role/dmz-sonarqube-backup
  bucket:   dmz-sonarqube-backup
  schedule: "25 1 * * *"
  image:    438423213058.dkr.ecr.eu-west-1.amazonaws.com/k8s/scripting-image:20210917153102
