apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: kops-check
  namespace: {{ .Values.namespace }}
spec:
  schedule: {{ .Values.schedule | quote }}
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 10
  successfulJobsHistoryLimit: 5
  startingDeadlineSeconds: 180
  suspend: {{ .Values.suspend }}
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            iam.amazonaws.com/role: {{ .Values.iamRole }}
            {{- if .Values.annotations }}
            {{ toYaml .Values.annotations }}
            {{- end }}
          labels:
            app: kops-check
        spec:
          containers:
          - name: main
            image: {{ .Values.image }}
            imagePullPolicy: IfNotPresent
            command:
            - /bin/bash
            - /aws/script
            env:
            - name: WEBHOOK_URL
              valueFrom:
                secretKeyRef:
                  name: kops-check
                  key: webhook.url
            {{- if .Values.environment }}
            {{- range $k, $v := .Values.environment }}
            - name: {{ $k }}
              value: {{ $v }}
            {{- end }}
            {{- end }}
            volumeMounts:
            - name: kops-check
              mountPath: /aws
          restartPolicy: OnFailure
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
          volumes:
          - name: kops-check
            configMap:
              name: kops-check
