apiVersion: crd.projectcalico.org/v1
kind: NetworkPolicy
metadata:
  name: default.kops-check
  namespace: {{ .Values.namespace }}
spec:
  order: 100
  selector:
    app == 'kops-check'
  types:
  - Egress
  egress:
  # Connect to kube2iam
  - action: Allow
    protocol: TCP
    destination:
      ports:
      - 8181
      selector: kubernetes.io/role in { 'node', 'master' }
      namespaceSelector: global()
  - action: Allow
    protocol: UDP
    destination:
      ports:
      - 53
      namespaceSelector: projectcalico.org/name == 'kube-system'
      selector: k8s-app == 'kube-dns'
  # S3 endpoint
  - action: Allow
    protocol: TCP
    destination:
      ports:
      - 443
      nets:
      - 52.0.0.0/8 # AWS S3 is using several IP's in this range
      - 54.0.0.0/8 # AWS S3 is using several IP's in this range
